version: '3.8'

services:
  store_manager_1:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    command: python -m src.controller.app
    volumes:
      - ../:/app
    environment:
      - INSTANCE_NUM=1
      - PROMETHEUS_METRICS_PORT=8080
    ports:
      - "8081:8080"
    networks:
      - monitoring_net
    container_name: store_manager_1

  store_manager_2:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    command: python -m src.controller.app
    volumes:
      - ../:/app
    environment:
      - INSTANCE_NUM=2
      - PROMETHEUS_METRICS_PORT=8080
    ports:
      - "8082:8080"
    networks:
      - monitoring_net
    container_name: store_manager_2

  store_manager_3:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    command: python -m src.controller.app
    volumes:
      - ../:/app
    environment:
      - INSTANCE_NUM=3
      - PROMETHEUS_METRICS_PORT=8080
    ports:
      - "8083:8080"
    networks:
      - monitoring_net
    container_name: store_manager_3

  store_manager_4:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    command: python -m src.controller.app
    volumes:
      - ../:/app
    environment:
      - INSTANCE_NUM=4
      - PROMETHEUS_METRICS_PORT=8080
    ports:
      - "8084:8080"
    networks:
      - monitoring_net
    container_name: store_manager_4

  store_manager_5:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    command: python -m src.controller.app
    volumes:
      - ../:/app
    environment:
      - INSTANCE_NUM=5
      - PROMETHEUS_METRICS_PORT=8080
    ports:
      - "8085:8080"
    networks:
      - monitoring_net
    container_name: store_manager_5

  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - store_manager_1
      - store_manager_2
      - store_manager_3
      - store_manager_4
      - store_manager_5
    networks:
      - monitoring_net
    container_name: nginx

  prometheus:
    image: prom/prometheus:latest
    ports:
      - '9091:9090'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--log.level=debug'
    networks:
      - monitoring_net
    container_name: prometheus
    depends_on:
      - store_manager_1
      - store_manager_2
      - store_manager_3
      - store_manager_4
      - store_manager_5

networks:
  monitoring_net:
    driver: bridge

volumes:
  grafana_data:
