services:
  store_manager:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    command: python -m src.Controller.store_manager
    ports:
      - "8080:8080"
    volumes:
      - ../:/app