global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'store_managers'
    static_configs:
      - targets: ['store_manager_1:8080', 'store_manager_2:8080', 'store_manager_3:8080']
    scrape_interval: 15s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 15s
