global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'auth_instances'
    static_configs:
      - targets: ['auth_instance_1:8080', 'auth_instance_2:8080']
  - job_name: 'product_instances'
    static_configs:
      - targets: ['product_instance_1:8080', 'product_instance_2:8080', 'product_instance_3:8080']
  - job_name: 'order_instances'
    static_configs:
      - targets: ['order_instance_1:8080', 'order_instance_2:8080', 'order_instance_3:8080', 'order_instance_4:8080', 'order_instance_5:8080']
  - job_name: 'other_instances'
    static_configs:
      - targets: ['other_instance_1:8080', 'other_instance_2:8080']
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
