@startuml Deployment View

skinparam {
    BackgroundColor #F5F5F5
    ActorBorderColor #333
    ComponentBorderColor #666
    ArrowColor #1E90FF
}

left to right direction

actor Caissier as caissier <<Person>>
actor Gestionnaire as gestionnaire <<Person>>
actor Dirigeant as dirigeant <<Person>>

cloud "Frontends" {
    component "Site Web" as site
}

node "Serveur d'Application" {
    frame "Docker Cluster" {
        [Kong Gateway] as kong
        [Auth Service] as auth
        [Order Service] as order
        [Product Service] as product
        [Reporting Service] as report

        database "PostgreSQL" as pg
        database "Redis" as redis
    }
}

' Connexions

caissier --> site : HTTPS
gestionnaire --> site : HTTPS
dirigeant --> site : HTTPS

site --> kong : /api/v2

kong --> auth : /auth
kong --> order : /orders
kong --> product : /products
kong --> report : /reports

order --> pg : ORM
product --> pg : ORM
report --> pg : SQL

order --> redis : Panier
product --> redis : Cache

cloud "Monitoring" {
    [Prometheus] as prom
}

prom --> kong : Metrics

@enduml
