@startuml Niveau2
skinparam {
  BackgroundColor #F5F5F5
  ComponentStyle rectangle
}

component "Docker container" as dc {
  component "Serveur Flask" as sf {
    [API] as api
    [Recherche de produits] as products
    [Sauvegarde de commandes] as orders
  }
  database "MySQL" as db
}

sf - api
api -- products
api -- orders
products --> db : ORM
orders --> db : ORM
sf - dc : API sur :8080
@enduml