@startuml ContexteTechnique

left to right direction

skinparam {
    BackgroundColor #F9F9F9
    ArrowColor #333333
    ComponentBorderColor #333333
    ComponentFontColor #333333
    DatabaseBorderColor #228B22
    QueueBorderColor #FF8C00
    InterfaceBorderColor #1E90FF
}

storage "Stock dans les enrepôts" as se

rectangle "Serveur physique" as sp {
    rectangle "Serveur Flask (Roule à partir d'un Dockerfile)" as sc {
        database "MySQL" as db #228B22
        rectangle Services {
            component "Gestion de l'authentification" as login #4FD880
            component "Gestion des produits" as products #FFD700
            component "Gestion des commandes" as orders #F55700
            component "Gestion des rapport" as reports #F56660
        }
    }
    sp -- sc : "Hosté sur le port :8080"
}

rectangle "Caisse 1" as c1
rectangle "Caisse 2" as c2
rectangle "Caisse 3" as c3

cloud {
    component "CI/CD Lab 1" as cicd #FF6347
    artifact "Site Web" as sw
}

db -> Services : "Persistance\nprincipale"
cicd ...> sc : "Vérification"

se -- db : Représentation digitale/physique

sw - sp : API
sc -- Services
sw -- c1
sw -- c2 : "API Rest"
sw -- c3

@enduml