@startuml ContexteTechnique

skinparam {
    BackgroundColor #F9F9F9
    ArrowColor #333333
    ComponentBorderColor #333333
    ComponentFontColor #333333
    DatabaseBorderColor #228B22
    QueueBorderColor #FF8C00
    InterfaceBorderColor #1E90FF
}

rectangle "Système Central" as sc {
    component "Gestion des Stocks" as stocks #FFD700
    component "Génération de rapports" as rapports #9370DB
    database "MySQL" as db #228B22
}

cloud {
    component "CI/CD Lab 1" as cicd #FF6347
    component "Docker Container" as docker #2496ED
}

rectangle "Caisse 1" as c1
rectangle "Caisse 2" as c2
rectangle "Caisse 3" as c3

stocks --> db : "Persistance\nprincipale"
rapports --> db : "Persistance\nprincipale"

cicd ...> sc : "Déploiement"
docker ...> sc : "Conteneurisation"


cloud {
    artifact "Site Web" as sw
}

sw - docker

sw ---- c1
sw ---- c2 : "API Rest"
sw ---- c3

note left of docker
    Contraintes d'intégration:
    - Doit coexister avec le CI/CD existant
    - Doit fonctionner en container Docker
end note

@enduml