@startuml UC3 - Visualiser les performances des magasins dans un tableau de bord

actor Employé as em
participant Interface as in
participant API as api
participant Controller as co
participant Service as se
database MySQL as db

em -> in : "Visualiser les performances des magasins"
in -> em : "Quelle magasin souhaitez-vous évaluer ?"
em -> in : store_id
in -> api : GET /performance/{store_id}
api -> co : getStorePerformance(store_id)
co -> se : getAllOrdersFromStore(store_id)
se -> db : SELECT * FROM orders WHERE store_id = :store_id
db --> se : Résultats
se --> co : Liste<Order>
co --> api : PerformanceDTO
api --> in : Affichage tableau de bord
in --> em : Affichage des performances

@enduml