@startuml ContexteMétier

left to right direction

skinparam {
  BackgroundColor #FFFFFF
  ArrowColor #003366
  ActorBorderColor #003366
  ActorFontStyle bold
  ActorFontColor #003366
  UsecaseBorderColor #003366
  UsecaseFontColor #003366
}

actor "Siège Social" as siege
actor "Employés\nde magasin" as employes
actor "Employés\nde magasin" as admin

rectangle "Système Central" as system {
  usecase "Recherche de stock" as products
  usecase "Consulter produits locaux" as cp
  usecase "Consulter produits centre réapprovisionnement" as cpr
  usecase "Réapprovisionner produits" as rp
  usecase "Gestion des commandes" as orders
  usecase "Enregistrer une commande" as ec
  usecase "Annuler une commande" as ac
  usecase "Génération de\nrapports consolidés" as rapports
  usecase "Voir les données de\n performance des instances" as stats
  usecase "Déployer les instances avec\n une configuration custom" as custom
  
}

products --> cp
products --> cpr
products --> rp
siege --> rapports : "Web (HTTPS/JSON)"
employes --> products : "Web (HTTPS/JSON)"
employes --> orders : "Web (HTTPS/JSON)"
orders --> ec
orders --> ac
admin --> stats : "Web (HTTPS/JSON)"
admin --> custom : "Web (HTTPS/JSON)"

@enduml