@startuml LogicalView

left to right direction

class Product {
  -id: int
  -name: str
  -category: str
  -stock_quantity: int
  -price: float
}

class Order {
  -id: int
  -user_id: datetime
  -price: list
  -products: float
  -status: float
}

Order "1" --> "*" Product

@enduml
