@startuml DeploymentView

node "Machine locale" {
  artifact "store_manager.py"

  database "BD SQLite" {
    artifact "database.db"
  }
}

node "Caisse" {
  artifact "console"
}

"store_manager.py" --> "database.db"

@enduml
