@startuml Niveau1
left to right direction

skinparam {
  BackgroundColor #F5F5F5
  ComponentBorderColor #333
  ComponentFontColor #333
}

rectangle "Docker container" {
  rectangle "Serveur Flask" as sf
  database "SQLite" as db
}


rectangle "Site Web LitElements Serveur node" as ui

sf --> db : ORM
ui --> sf : http

@enduml