@startuml Niveau1
left to right direction

skinparam {
  BackgroundColor #F5F5F5
  ComponentBorderColor #333
  ComponentFontColor #333
}

rectangle "Serveur physique" {
  rectangle "Instances Docker Kong" as sk
  rectangle "Instances Docker Flask" as sf
  database "SQLite" as db
}

rectangle "Site Web" as ui

ui --> sk : http
sk "1" --> "*" sf : API Gateway
sf --> db : ORM

@enduml