@startuml ContexteTechnique

left to right direction

skinparam {
    BackgroundColor #F9F9F9
    ArrowColor #333333
    ComponentBorderColor #333333
    ComponentFontColor #333333
    DatabaseBorderColor #228B22
    QueueBorderColor #FF8C00
    InterfaceBorderColor #1E90FF
}

left to right direction

' ==== Clients ====
rectangle "Clients" as clients {
    artifact "Site Web" as web
}

' ==== Magasin ====
rectangle "Magasin" as mag {
    artifact "Site Web" as web
    rectangle "Caisse 1" as c1
    rectangle "Caisse 2" as c2
    rectangle "Caisse 3" as c3
}

rectangle "Serveur physique" {

    ' ==== Containers ====
    rectangle "Kong Gateway" as kong {
        interface "API:80" as api
        interface "Admin:8001" as admin
    }

    rectangle "Auth Service" as auth #FFAAAA {
        component "Instance 1\n:8080" as auth1
        component "Instance 2\n:8081" as auth2
    }

    rectangle "Product Service" as prod #AAFFAA {
        component "Instance 1\n:8080" as prod1
        component "Instance 2\n:8081" as prod2
    }

    rectangle "Order Service" as order #AAAAFF {
        component "Instance 1\n:8080" as order1
        component "Instance 2\n:8081" as order2
    }

    rectangle "Other Service" as other #FFAAFF {
        component "Instance 1\n:8080" as other1
    }

    rectangle "Monitoring" as monit {
        component "Prometheus\n:9090" as prom
        component "Redis Exporter\n:9121" as rexp
    }

    database "PostgreSQL\n:5432" as pg
    database "Redis\n:6379" as redis
}



storage "Stock Physique" as stock

' ==== Connexions ====
' Clients vers Kong
web -r-> api
c1 --> web
c2 --> web
c3 --> web

' Kong vers Services
api -d-> auth1 : /auth
api -d-> auth2
api -d-> prod1 : /products
api -d-> prod2
api -d-> order1 : /orders
api -d-> order2
api -d-> other1 : /other

' Services vers Bases
auth1 -u-> pg
auth2 -u-> pg
prod1 -u-> pg
prod2 -u-> pg
order1 -u-> pg
order2 -u-> pg
other1 -u-> pg

auth1 -u-> redis
auth2 -u-> redis
prod1 -u-> redis
prod2 -u-> redis
order1 -u-> redis
order2 -u-> redis
other1 -u-> redis

' Monitoring
prom -u-> auth1 : /metrics
prom -u-> auth2
prom -u-> prod1
prom -u-> prod2
prom -u-> order1
prom -u-> order2
prom -u-> other1
prom -u-> rexp
rexp -u-> redis

' Stock
stock -u-> pg : Sync

@enduml